### ISSUE TITLE
使用该插件会导致前台报500错误

### ISSUE THREAD

**Issue by 2451611170** [guqing/plugin-cloudinary#1]
已经正确配置插件，但是只要一启用插件就会报服务器内部错误（500）
![2024-03-23 150856](https://github.com/guqing/plugin-cloudinary/assets/85246873/5d98d139-adda-4148-b1c7-299872628401)

**Comment by guqing** [comment]
提供一下日志呢

**Comment by 2451611170** [comment]
> 提供一下日志呢

2024-03-23T00:02:23.796+08:00 ERROR 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] r.h.a.e.controller.DefaultController     : Reconciler in com.stonewu.sitepush.reconciler.PostPushReconciler-worker-1 aborted with an error, re-enqueuing...

java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Unknown Source) ~[na:na]
	at com.stonewu.sitepush.reconciler.PostPushReconciler.reconcile(PostPushReconciler.java:35) ~[na:na]
	at com.stonewu.sitepush.reconciler.PostPushReconciler.reconcile(PostPushReconciler.java:21) ~[na:na]
	at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[api-2.13.1.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2024-03-23T00:02:23.800+08:00 ERROR 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] r.h.a.e.controller.DefaultController     : Reconciler in com.stonewu.sitepush.reconciler.PostPushReconciler-worker-1 aborted with an error, re-enqueuing...

**Comment by guqing** [comment]
从日志来看，你这个日志与本插件没有任何关系，可能是日志不对，使用的什么主题呢我可以用跟你一样的主题来排查一下，如果没有复现则应该不是本插件的问题，再此之前你可以尝试一下，停止所有插件访问看是否报错，如果不报错则只启用本插件来访问以确保是因为本插件导致的问题

**Comment by 2451611170** [comment]
> 从日志来看，你这个日志与本插件没有任何关系，可能是日志不对，使用的什么主题呢我可以用跟你一样的主题来排查一下，如果没有复现则应该不是本插件的问题，再此之前你可以尝试一下，停止所有插件访问看是否报错，如果不报错则只启用本插件来访问以确保是因为本插件导致的问题

关闭了所有插件，只启用了这个插件，还是会报500，用的Joe3.0主题

**Comment by guqing** [comment]
> > 从日志来看，你这个日志与本插件没有任何关系，可能是日志不对，使用的什么主题呢我可以用跟你一样的主题来排查一下，如果没有复现则应该不是本插件的问题，再此之前你可以尝试一下，停止所有插件访问看是否报错，如果不报错则只启用本插件来访问以确保是因为本插件导致的问题
> 
> 
> 
> 关闭了所有插件，只启用了这个插件，还是会报500，用的Joe3.0主题

感谢反馈 我将使用 Joe3.0 主题来尝试复现此问题，并尽快回复你❤️

**Comment by guqing** [comment]
已经确认是此插件的问题，已经修复，等后续发布版本后尝试或者下载下面给出的 zip 包解压缩后安装使用，不过观察到 Joe3.0 主题有随机图功能，随机图的 URL 可能无法支持，这会导致无法访问到图片

[plugin-cloudinary.zip](https://github.com/guqing/plugin-cloudinary/files/14732115/plugin-cloudinary.zip)
